name: Deploy webapp to EC2
on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: production
    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}

    steps:
      - uses: actions/checkout@v4

      - name: Create release archive
        run: |
          tar --exclude='.git' \
              --exclude='node_modules' \
              --exclude='release.tgz' \
              --warning=no-file-changed \
              -czf release.tgz .

      - name: Copy bundle to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: release.tgz
          target: /home/ec2-user/app
          overwrite: true

      - name: Execute remote script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -euxo pipefail
            mkdir -p /home/ec2-user/app
            cd /home/ec2-user/app
            tar xzf release.tgz --overwrite
            chmod +x start_next.sh
            ./start_next.sh &
            exit 0
